# This file contains vars used to configure the build system (build.py)
# Some values may be omitted, in this case the defaults are used

#build_dir: build
#changeset_dir: changeset

# directory where exercises are packed
exc_dir: exercises

# subdir inside `exc_dir` where howto images are put
img_subdir: img

# Path to Free-Exercise-DB Git submodule
# specified relative to build.py directory
freedb_dir: deps/free-exercise-db

# how each freedb data file will be named
freedb_exc_json: data.json