"""Grabs videos from a remote source, cuts and processes them based on a spec.

Dependencies: yt-dlp, ffmpeg, ffprobe (part of ffmpeg)
"""

from dataclasses import dataclass, field
import functools
import io
import inspect
import itertools
import json
import pathlib as pth
import re
import reprlib
import shutil
import subprocess as sp
import sys
import tempfile
import typing as t
from yt_dlp import YoutubeDL as YDL

type AnyPath = pth.Path | str

TOOL_NAME = pth.Path(__file__).stem

# What is used to split cut entries in `concat_format`
CUT_REGEXP = r'((?:\.{3})|(?:(?:\d+:)?(?:\d{0,2}:)?\d{0,2}\.?\d{0,3}))'
CUT_REGEXP = re.compile(f'{CUT_REGEXP} - {CUT_REGEXP}')

# Parses ffmpeg status line like the following into groups
# 'frame=  109 fps=0.0 q=-0.0 size=N/A time=00:00:02.20 bitrate=N/A speed=4.41x    '
# 'frame=  577 fps=0.0 q=-1.0 Lsize=   13053KiB time=00:00:20.08 bitrate=5322.7kbits/s speed= 338x    '
FF_STATUS_RE = (r'^'
    r'frame=\W*(?P<frame> \d+ )  \W'
    r'fps=(?P<fps> \d+ .? \d* )  \W'
    r'q=(?P<q> \-? \d+ .? \d* )  \W'
    r'L?size=\W*(?P<size> (?:N/A) | \d+ \w? ) \w*   \W'     # 'K', 'M' suffix -> result
    r'time=(?P<time> \d{2} \: \d{2} \: \d{2} \. \d{2} )  \W'
    r'bitrate=(?P<bitrate> (?:N/A) | \d+ \.? \d* \w? ) [\w/]*  \W'  # 'k', 'm' suffix -> result
    r'speed=\W*(?P<speed> \d+ \.? \d* ) x'
    r'\W* $'     # they're always ending with 4 spaces
)
FF_STATUS_RE = re.compile(FF_STATUS_RE, flags=re.VERBOSE)
def ffmpeg_parse_status(line: str) -> dict | None:
    """Parse ffmpeg output line, trying to get status from it.

    Returns:
        A dict filled with properly formatted status entries.
        None if status information was not found in the line
    """
    match = FF_STATUS_RE.match(line)
    if match is None:
        return None
    res = match.groupdict()
    
    # replace 'N/A' with None
    res = {k: (None if v == 'N/A' else v) for k, v in res.items()}

    # all suffixes to bits and bytes
    for field, is_bytes in [['size', True], ['bitrate', False]]:
        if res[field] is None:
            continue
        # split out multiplier and value
        mul = ''.join([c for c in res[field] if not c.isdigit()])
        lookup = [
            {'': 1, 'k': 1000, 'm': 1000 * 1000, 'g': 1000 * 1000 * 1000},
            {'': 1, 'k': 1024, 'm': 1024 * 1024, 'g': 1024 * 1024 * 1024}
        ]
        mul = lookup[is_bytes][mul.tolower()]
        val = int(res[field].replace(mul, ''))
        res[field] = val * mul
    
    # convert other numeric values as well
    for field in 'frame', 'fps', 'q', 'speed':
        if res[field] is None:
            continue
        conv = int if field == 'frame' else float
        res[field] = conv(res[field])
    
    return res


def concat_format(videofile: AnyPath, cuts: t.Iterable[str], *,
                  is_add_header: bool = True) -> str:
    """Formats specified video cut fragments into ffmpeg concat demuxer format.

    Notes:
        See concat demuxer documentation:
          - https://trac.ffmpeg.org/wiki/Concatenate#demuxer
          - https://ffmpeg.org/ffmpeg-formats.html#concat

    Args:
        videofile: Path to input video
        cuts: an iterable with good videofile fragments, where each fragment
            is an str of the form: '[ts_from] - [ts_to]'.

            `[ts_from]` and `[ts_to]` are timestamps in ffmpeg usual format:
            `HH:MM:SS[.frame]` (`.frame` - is the optional frame number in
            that second).

            One of `[ts_from]` or `[ts_to]` can be given as `...`, meaning
            the start or the end of the videofile (`inpoint` or `outpoint`
            will be skipped in the resulting concat output).

            For example, ['... - 00:00:05', '00:00:07 - 00:00:08.12', '00:00:10 - ...']
            will result in video: (start to 5s) + (7s to 8 + 12/fps s) + (10s to end)
        is_add_header: optional argument, defining whether the resulting concat
            should have a usual `ffconcat version 1.0` header at the first line.
            Useful when outputs from numerous files are combined together,
            in the case only the first one needs to have this header.
    Returns:
        An output string, ready to be fed into ffmpeg concat demuxer input
    """
    videofile = pth.Path(videofile)

    lines = []

    if is_add_header:
        lines += ['ffconcat version 1.0']
    lines += [f'# BEGIN Autogenerated portion for file {videofile}']

    if not cuts:    # empty
        lines += [f"file '{videofile}'"]

    for ix, cut in enumerate(cuts, 1):
        match = CUT_REGEXP.fullmatch(cut)
        if not match:
            raise ValueError(f'Wrong cut {cut} for file {videofile}')
        
        begin, end = match.groups()

        lines += [f"file '{videofile}'"]
        if begin != '...':
            lines += [f'inpoint {begin}']
        if end != '...':
            lines += [f'outpoint {end}']
        if ix < len(cuts):  # when not last line
            lines += ['']   # empty line for readability
    
    lines += ['# END autogenerated portion', '']
    
    return '\n'.join(lines)


def prepare_args(dct: dict, *, prefixes=('-', None), kvseps=(None, '='), lstsep=','):
    """Formats arguments according to spec.

    Args:
        prefixes: what to put before key at each hierarchy level,
                  i.e. '--' means {'k': 'v'} will be '--k ...'
        kvseps: separators to join keys and values at each level,
                i.e. '=' means {'k': 'v'} will be '--k=v'.
                None means keys and values need to be put as separate elements
        lstsep: separator between value list,
                i.e. ':' means ('coffee', 'is', 'good') becomes 'coffee:is:good'
    """
    def parse_level(data, level=0):
        prefix = prefixes[level]
        kvsep = kvseps[level]
        
        col = []

        for k, v in data.items():
            k = (prefix or '') + k

            if isinstance(v, dict):     # here we go again
                # sure could have done it with no recursion, but must be readable
                subvals = parse_level(v, level + 1)
                for sv in subvals:
                    col += [k, sv] if kvsep is None else [k + kvsep + sv]

                continue

            if isinstance(v, str) and not v:        # empty string -> just the key
                col += [k]
                continue

            if not isinstance(v, str):  # assume something iterable -> join it
                v = lstsep.join(v)

            if isinstance(v, str):
                col += [k, v] if kvsep is None else [k + kvsep + v]
                continue
            
            raise RuntimeError(f"Ewww, '{k}': '{v}'... What are you feeding me with?")

        return col
    
    return parse_level(dct)


def get_executable(executable: AnyPath) -> str:
    """A small helper to get the executable name for running subprocess"""
    executable = pth.Path(executable)
    # We need to use fully-qualified path to executable
    # per https://docs.python.org/3/library/subprocess.html#subprocess.Popen
    bin = shutil.which(executable)
    if bin is None:
        raise RuntimeError(f'Executable {executable} path not found')
    return bin


# Default arguments to ffprobe in form of an input to `prepare_args`
FFPROBE_ARGS: dict = {
    'loglevel': 'error',        # filter-out unusable data
    'print_format': 'json',     # we'll parse that
    # 'select_streams': 'v',      # only all video streams'
    'show_entries': {
        'stream': '',
        'format': ''
    }
}

def ffprobe_wrap(videofile: AnyPath, *,
                 extra_args: dict = {}, is_verbose: bool = True,
                 ffprobe_path: AnyPath = 'ffprobe'):
    """A wrapper to call ffprobe and get information on the video file."""
    videofile = pth.Path(videofile)
    assert videofile.exists(), f'File {videofile} not found'

    args = [get_executable(ffprobe_path)]

    kwa = dict(FFPROBE_ARGS)
    kwa.update(extra_args)
    args += prepare_args(kwa, prefixes=('-', None), kvseps=(None, '='), lstsep=',')

    args.append(str(videofile))
    if is_verbose:
        print(' '.join(args), file=sys.stderr)
    out = sp.run(args, capture_output=True, text=True)
    out.check_returncode()

    res = json.loads(out.stdout)
    return res


def sp_lines_iter(proc: sp.Popen, *, poll_s: int | None, proc_stream: io.TextIOBase | str):
    if proc_stream in ['stout', 'stderr']:
        proc_stream = getattr(proc, proc_stream)

    while True:
        try:
            proc.wait(poll_s)
        except sp.TimeoutExpired:
            pass
        else:   # process terminated
            yield from proc_stream      # residual lines
            return         # end iteration
        
        # current lines
        yield from proc_stream

def ffmpeg_progress_iter(lines, outbuf):
    for line in lines:
        status = ffmpeg_parse_status(line)
        if status is None:
            outbuf.write(line)
            continue
        
        # reached status line, output it as progress
        yield status

FFMPEG_PRE_ARGS = {
    'hide_banner': '', 
    'hwaccel': 'auto'
}

FFMPEG_ARGS_GET_LOUDNORM = {
    'ac': '1',
    'af': ['loudnorm', 'print_format', 'json'],
    'f': 'null',
    '': ''
}
def ffmpeg_wrap(infile: AnyPath, *, args: dict,
                outfile: AnyPath | None = None,
                pre_args: dict = FFMPEG_PRE_ARGS,
                is_verbose: bool = True,
                ffmpeg_path: AnyPath = 'ffmpeg',
                poll_interval_ms: int = 100):
    """Wraps an ffmpeg subrocess call.

    Args:
        args: ffmpeg arguments (in `prepare_args()` format),
            to be placed *after* the `infile`
        outfile: Output file (optional, but usually needed)
        pre_args: Arguments to ffmpeg *before* the `infile`
        is_verbose: optional flag, whether to echo ffmpeg output
        ffmpeg_path: optional path to ffmpeg binary
    Note:
        Output buffer is designed to contain raw ffmpeg log output without
        the progress lines.
        It gets filled with initial ffmpeg output, before the progress lines
        and is guaranteed to have that data at call return.
        But to get any further data into that buffer, the output iterator
        needs to be consumed.
    """
    pargs = [get_executable(ffmpeg_path)]

    prepare = functools.partial(prepare_args,
        prefixes=('-', None), kvseps=(None, '='), lstsep='=')

    pargs += prepare(pre_args)      # formatted args before the input file
    pargs += ['-i', str(infile)]    # input file itself
    pargs += prepare(args)          # and after the file
    if outfile is not None:
        pargs += [str(outfile)]  # output goes last
    
    if is_verbose:
        print(' '.join(pargs), file=sys.stderr)
    
    proc = sp.Popen(pargs, stderr=sp.PIPE, text=True)

    line_ix = sp_lines_iter(proc, poll_s=poll_interval_ms / 1000.0,
                                  proc_stream=proc.stderr)

    # Get all data before ffmpeg starts spitting its progress

    # This will store results, having all progress lines filtered-out
    outbuf = io.StringIO()          # Fast buffer without line wrapping

    progress_ix = ffmpeg_progress_iter(line_ix, outbuf)
    firststatus = next(progress_ix)     # advance iter to the first progress item

    # reconstruct iter, with 1st item back in place
    progress_ix = itertools.chain([firststatus], progress_ix)

    return proc, progress_ix, outbuf


# @TODO: implement this
def extract_loudnorm():
    ...
    '''
    '[Parsed_loudnorm_0 @ 0x7c7454002680] ',
    '{',
    '\t"input_i" : "-19.12",',
    '\t"input_tp" : "-1.82",',
    '\t"input_lra" : "13.60",',
    '\t"input_thresh" : "-29.79",',
    '\t"output_i" : "-25.78",',
    '\t"output_tp" : "-9.72",',
    '\t"output_lra" : "5.60",',
    '\t"output_thresh" : "-35.92",',
    '\t"normalization_type" : "dynamic",',
    '\t"target_offset" : "1.78"',
    '}',
    '[out#0/null @ 0x5a6d9e9c7bc0] video:288KiB audio:10493KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown'
    '''
    

class VideoSpec:
    name: str   # property to get names based on outfile name set

    url: str
    outfile: pth.Path
    builddir: pth.Path
    metadata: dict | None = None    # @FIXME: avoid very long output via repr
    downloaded: pth.Path | None = None      # result after downloading
    downloaded_info: dict | None = None     # ffprobed info on downloaded file
    merged: pth.Path | None = None          # result after cutting

    is_verbose: bool = False

    _tmpdir: tempfile.TemporaryDirectory | None = field(default=None, repr=False)

    # Whether to overwrite files. Class-level default
    is_overwrite: bool = False
    
    TEMPLATES = {
        'meta_json':  '{name}.meta.json',   # Template for json filenames
        'downloaded': '{name}.dl.mkv',      # Downloaded file name
        'merged':     '{name}.merged.mkv'   # Name of file after cut & merge
    }

    FFPROBE_PATH: pth.Path = pth.Path('ffprobe')

    def __init__(self, url: str, outfile: AnyPath,
                 builddir: AnyPath | None = None,
                 *,
                 is_overwrite: bool | None = None,
                 is_verbose: bool | None = None):
        """
        Args:
            url: Where to grab the video from
            outfile: Where to store the result
            builddir: Processing directory.
                      When not provided, creates a tmp directory.
        """
        self.url = url
        self.outfile = pth.Path(outfile)
        # set here, or set to tmpdir lazyly created in _ensure_builddir
        if builddir is not None:
            builddir = pth.Path(builddir)
            builddir.mkdir(exist_ok=True)       # create if doesn't exist
            self.builddir = builddir
            
            # set downloaded and cut paths as well if found
            for field in self.TEMPLATES:
                path = builddir.joinpath(self._filename_for(field))
                if path.exists():
                    setattr(self, field, path)

        if is_overwrite is not None:    # otherwise use class-level default
            self.is_overwrite = is_overwrite
        if is_verbose is not None:    # otherwise use class-level default
            self.is_verbose = is_verbose

    @property
    def name(self):
        return self.outfile.stem
    
    def _filename_for(self, fieldname: str):
        """A helper to get a formatted filename for entries out of TEMPLATES"""
        tpl = self.TEMPLATES[fieldname]
        return tpl.format(name=self.name)

    def _ensure_builddir(self):
        if self.builddir is None:
            prefix = f'{TOOL_NAME}_{self.name}_'
            self._tmpdir = tempfile.TemporaryDirectory(prefix=prefix)
            self.builddir = pth.Path(self._tmpdir.name)
    
    def __repr__(self):     # do things ourselves
        fields = inspect.get_annotations(type(self))
        fields = {k: getattr(self, k) for k in fields
                  if not k.startswith('_') and not k.isupper()}
        # translate paths to str
        res = {k: str(v) if isinstance(v, pth.Path) else v
               for k, v in fields.items()}
        # long names come short
        long = {field: '{...}' if res[field] else repr(res[field])
                for field in ['metadata', 'downloaded_info']}

        formatted = [(f'{k}={v!r}' if k not in long else f'{k}={long[k]}')
                     for k, v in res.items()]
        res = ', '.join(formatted)
        return f'{type(self).__name__}({res})'


    def get_metadata(self, *, shorten: bool = True, is_set_own: bool = True,
                     is_overwrite: bool | None = None):
        """Gets pure metadata for a given entry.

        Note:
            Because of poor YDL architecture, calling this alongside with
            `download()` will cause 2 queries instead of one.
            So, using `download()` is preferrable, as it fills the metadata
            field anyway. This allows to avoid double-querying.
        """

        is_overwrite = is_overwrite if is_overwrite is not None else self.is_overwrite
        json_name = self._filename_for('meta_json')
        json_path = (self.builddir is not None and self.builddir.joinpath(json_name))
        
        # Try getting it from build directory if possible
        if not is_overwrite and json_path is not None and json_path.exists():
            with open(json_path, 'r') as f:
                meta = json.load(f)
        else:      # wasn't possible, get it ourselves
            print("@FIXME: REDOWNLOADING METADATA")
            # {'forcejson': True, 'noprogress': True, 'quiet': True, 'simulate': True}
            with YDL({'noprogress': True, 'quiet': True}) as dl:
                meta = dl.extract_info(self.url, download=False, process=False)
            
            # dump it into directory if possible
            if json_path is not None:
                with open(json_path, 'w') as f:
                    json.dump(meta, f, indent=2)

        # filter-out long parts
        if shorten:
            meta = {k: v for k, v in meta.items() if (not k.startswith('_')
                    and not k in ['formats', 'automatic_captions', 'thumbnails']) }

        if is_set_own:
            self.metadata = meta
        
        return meta


    def download(self, *, is_overwrite: bool | None = None):
        """Downloads raw video from a specified remote resource.

        Args:
            is_overwrite: Whether the video file should be overwriten.
                Otherwise, if the downloaded video already exists, no actual
                download is performed and the object state gets filled from
                the exising files.
        """
        is_overwrite = is_overwrite if is_overwrite is not None else self.is_overwrite

        self._ensure_builddir()
        
        # where to put downloaded file
        dlout = self.builddir.joinpath(self._filename_for('downloaded'))
        jsonout = self.builddir.joinpath(self._filename_for('meta_json'))

        if not dlout.exists() or is_overwrite:
            cfg = {     # --print-to-file "%()j" outfile.meta.json -o "outfile.dl.mkv"
                'outtmpl': {'default': str(dlout)},
                'print_to_file': {'video': [('%()j', str(jsonout))]},
                'noprogress': True,
                'quiet': True
            }
            with YDL(cfg) as dl:
                retcode = dl.download(self.url)

        # metadata should be also present, so fill it
        self.get_metadata(is_set_own=True, is_overwrite=False)
        self.downloaded = dlout
        return dlout, jsonout

    def probe(self, *, extra_args: dict = {},
              is_reprobe: bool | None = None, is_verbose: bool | None = None):
        """Gets the information on a downloaded file using ffprobe"""
        # @TODO: add more processing
        assert (isinstance(self.downloaded, pth.Path) and self.downloaded.exists()
               ), 'Downloaded file does not exist'
                
        is_reprobe = is_reprobe if is_reprobe is not None else self.is_overwrite
        is_verbose = is_verbose if is_verbose is not None else self.is_verbose

        if is_reprobe or self.downloaded_info is None:
            self.downloaded_info = ffprobe_wrap(self.downloaded,
                                                  extra_args=extra_args,
                                                  is_verbose=is_verbose)

        return self.downloaded_info
    
    def cut(self):
        ...

def process(spec: VideoSpec):
    ...


if __name__ == '__main__':
    testspec = {
        'url': 'https://www.youtube.com/watch?v=OgR9CnNHCc0',
        'outfile': 'IDEAS/preacher-curl.mp4',
        'builddir': 'IDEAS/videograb-tmp'
    }
    spec = VideoSpec(**testspec, is_verbose=True)
    dl, meta = spec.download()
    probed = spec.probe()